language: node_js
node_js:
  - "10"
cache:
  yarn: true
branches:
  only:
    - write
git:
  depth: 1
install: "npm install"
script: "hexo generate"
deploy:
  local_dir: public
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: write